variables:
  IMAGE_TEST_1: docker.io/jredmond/type_1_image:1
  IMAGE_TEST_2: docker.io/jredmond/type_2_image:1
  IMAGE_TEST_3: docker.io/jredmond/type_3_image:1
  WORKAROUND_TEST_1: docker.io/jredmond/type_1_image:1
  WORKAROUND_TEST_2: docker.io/jredmond/type_2_image:1
  WORKAROUND_TEST_3: docker.io/jredmond/type_3_image:1
